# Site settings
title: Code Paper Scissors
email: tech@alittlemarket.fr
description: "The Etsy France technical team publishes here articles related to software development: Symfony, PHP, MySQL, Nginx, Varnish, Redis ..."
baseurl: "" # empty to allow site to be runned via 127.0.0.1:4000
url: "http://codepaperscissors.com"
twitter_username: CodePaprScissrs
github_username:  alittlemarket

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: "" # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# blog cover
cover: "/assets/images/img4.jpg"
logo: "/assets/images/logoblanc.png"

# blog authors
authors:
  antoine:
    name: Antoine Froger
    display_name: Antoine
    avatar: https://avatars0.githubusercontent.com/u/3509631?v=3&s=400
    email: antoine@alittlemarket.fr
    twitter: __tooni__
    github: antfroger
    active: false
  arnaud:
    name: Arnaud Pflieger
    display_name: Arnaud
    avatar: https://avatars0.githubusercontent.com/u/3698901?v=3&s=400
    email: arnaud@alittlemarket.fr
    twitter: ArnaudPflieger
    github: apflieger
  celine:
    name: Celine Coelho
    display_name: Celine
    avatar: https://avatars0.githubusercontent.com/u/8169949?v=3&s=400
    email: celine@alittlemarket.fr
    twitter: _cissou_
    github: alittleceline
  kevin:
    name: Kevin Aboudarham
    display_name: Kevin
    avatar: https://avatars1.githubusercontent.com/u/4158775?v=3&s=400
    email: kevin@alittlemarket.fr
    twitter: darame07
    github: darame07ALM
  jonathan:
    name: Jonathan Bouaziz
    display_name: Jonathan
    avatar: https://avatars3.githubusercontent.com/u/8112574?v=3&s=400
    email: jonathan@alittlemarket.fr
    twitter: jbouaziz
    github: JonathanBouaziz
  laurent:
    name: Laurent Callarec
    display_name: Laurent
    avatar: https://avatars0.githubusercontent.com/u/6905322?v=3&s=400
    email: laurent@alittlemarket.fr
    twitter: sitesAlittle
    github: laurent-callarec
  matthieu:
    name: Matthieu Rollin
    display_name: Matthieu
    avatar: https://avatars2.githubusercontent.com/u/2761725?v=3&s=400
    email: matthieu@alittlemarket.fr
    twitter: sitesAlittle
    github: matthieu-rollin
  nick:
    name: Nick Jouannem
    display_name: Nick
    avatar: https://avatars2.githubusercontent.com/u/960935?v=3&s=400
    email: nick@alittlemarket.fr
    twitter: njouannem
    github: Nickology
  olivier:
    name: Olivier Garcia
    display_name: 0livier
    avatar: https://avatars1.githubusercontent.com/u/10607?v=3&s=460
    email: olivier@alittlemarket.fr
    twitter: 0livier
    github: 0livier
  qikai:
    name: Qikai Gu
    display_name: Qikai
    avatar: https://avatars2.githubusercontent.com/u/7137183?v=3&s=400
    email: qikai@alittlemarket.fr
    twitter: QikaiGu
    github: Qikai-ALM
  romain:
    name: Romain Ardiet
    display_name: Romain
    avatar: https://avatars2.githubusercontent.com/u/2420675?v=3&s=400
    email: romaina@alittlemarket.fr
    twitter: RomainArdiet
    github: Romibuzi
  sylvaina:
    name: Sylvain Artois
    display_name: Sylvain
    avatar: https://avatars2.githubusercontent.com/u/6448828?v=3&s=400
    email: sylvaina@alittlemarket.fr
    twitter: dye_pop
    github: sylvaina-artois
  sylvainm:
    name: Sylvain Mauduit
    display_name: Sylvain
    avatar: https://avatars3.githubusercontent.com/u/545340?v=3&s=400
    email: sylvain@alittlemarket.fr
    twitter: Swop
    github: Swop
  thierry:
    name: Thierry Gerbeau
    display_name: Thierry
    avatar: https://avatars0.githubusercontent.com/u/4618811?v=3&s=400
    email: thierry@alittlemarket.fr
    twitter: sitesAlittle
    github: thierrygerbeau
  vincent:
    name: Vincent Paulin
    display_name: Vincent
    avatar: https://avatars0.githubusercontent.com/u/4487845?v=3&s=400
    email: vincent@alittlemarket.fr
    twitter: genokilller
    github: VincentPaulinALM
  zouhir:
    name: Zouhir Bahij
    display_name: Zouhir
    avatar: https://avatars0.githubusercontent.com/u/6905145?v=3&s=400
    email: zouhir@alittlemarket.fr
    twitter: zbahij
    github: zouhirB