# Site settings
title: AlittleCode
email: tech@alittlemarket.fr
description: "The alittlemarket technical team publish here articles related to software development: Symfony, PHP, MySQL, Nginx, Varnish, Redis ..."
baseurl: "http://alittlemarket.github.io/"
url: "http://alittlemarket.github.io/"
twitter_username: AlittleMarket
github_username:  alittlemarket

# Build settings
markdown: kramdown
permalink: pretty
